name: Export Dexdump Fast

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "build-tools;34.0.0"
      - run: cp "$ANDROID_HOME/build-tools/34.0.0/dexdump" ./dexdump && chmod +x ./dexdump
      - uses: actions/upload-artifact@v4
        with:
          name: dexdump-linux-fast
          path: dexdump
          if-no-files-found: error
